### ISSUE TITLE
Add launch.json and/or tasks.json?

### ISSUE THREAD

**Issue by cmeeren** [MangelMaxime/fulma-demo#18]
Do you think this demo could benefit from defining a VS Code `launch.json` and/or `tasks.json`? Most other Fable samples/templates I have seen have this, see e.g. [fable-templates/simple](https://github.com/fable-compiler/fable-templates/tree/master/simple/Content/.vscode), [fable-templates/electron](https://github.com/fable-compiler/fable-templates/tree/master/electron/Content/.vscode), [SAFE-Stack/SAFE-BookStore](https://github.com/SAFE-Stack/SAFE-BookStore/tree/master/.vscode).

I haven't used VS Code or Fable much yet, so I wouldn't really know where and when these are useful and where they don't add much.

**Comment by MangelMaxime** [comment]
I don't know, I personnaly almost never use them and prefer to launch commands from the terminal because there is only 2 commands.

But if someone wants to add it the demo I will aceept the PR.

**Comment by cmeeren** [comment]
Thanks, I'll keep it in mind if/when I have properly started with Fable and VS Code. No promises of course, anyone else feel free to do something about this too.

**Comment by cmeeren** [comment]
This may be a stupid question, but how to you debug from VS Code (hitting breakpoints etc.)? Is that possible without a launch task?

**Comment by MangelMaxime** [comment]
No idea :) I don't use the debugger ^^

If you want to debug an Elmish app from VSCode people use the chrome debugger extension I think but I don't know how to set it up.

I don't use the debugger because I have redux dev tool to explore my Model if needed and because the model controlling everything it is enough. Otherwise, I log some function result when needed.

**Comment by cmeeren** [comment]
Fair enough, thanks.
