### ISSUE TITLE
Unable to build - Debian

### ISSUE THREAD

**Issue by CraigChamberlain** [MangelMaxime/fulma-demo#37]
Tried several dotnet sdks.  I can provide verbose script but thought you might just have a suggestion for some command to run to make it all work.  What version of .net have you tested up to?

**Comment by MangelMaxime** [comment]
Hello @CraigChamberlain,

I just reworked the repo by upgrading the dependencies and making it require only .NetCore 3.

Can you please check if you have .NetCore 3 installed and check again?

I also took this opportunity to add Gitpod support so now, you can click in the link "Open in Gitpod" in the README.md and it will start a workspace for you in the browser. (no need to install anything)

**Comment by CraigChamberlain** [comment]
Many thanks.  I'll look again.  I'm starting to get to know my way around yarn, paket and fake.  Paket has been completely changed recently and I think that has something to do with it?  I think I had to update a few packages with yarn on another template of yours to get it to compile.  I also went too far with one and updates so much it all broke :(

**Comment by CraigChamberlain** [comment]
I can confirm this is completely fixed and all working perfectly.  Many thanks.

**Comment by MangelMaxime** [comment]
Happy that your problem has been solved.

And yes, some of my templates have not been updated since a long time and even by locking the dependencies sometimes, it breaks because we have a newer version of node.js or netcore installed.

It is not easy to detect these things. Hopefully Gitpod, now helps to mitigate the issue a bit for demos. :)
